services:
  mysql-clientes:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_clientes
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - clientes_data:/var/lib/mysql
      - ./ms-clientes/src/main/resources/bd-clientes.sql:/docker-entrypoint-initdb.d/init.sql

  ms-clientes:
    build: ./ms-clientes
    depends_on:
      - mysql-clientes
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-clientes:3306/bd_clientes
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpass
      SERVER_PORT: 8081
    ports:
      - "8081:8081"

  mysql-logistica:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_logistica
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - logisticas_data:/var/lib/mysql
      - ./ms-logistica/src/main/resources/bd-logistica.sql:/docker-entrypoint-initdb.d/init.sql

  ms-logistica:
    build: ./ms-logistica
    depends_on:
      - mysql-logistica
      - ms-clientes
      - osrm
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-logistica:3306/bd_logistica
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpass
      SERVER_PORT: 8082
      MS_CLIENTES_URL: http://ms-clientes:8081/api/v0.1
      OSRM_BASE_URL: http://osrm:5000
    ports:
      - "8082:8082"

  mysql-tarifas:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_tarifas
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - tarifas_data:/var/lib/mysql
      - ./ms-tarifas/src/main/resources/bd-tarifas.sql:/docker-entrypoint-initdb.d/init.sql

  ms-tarifas:
    build: ./ms-tarifas
    depends_on:
      - mysql-tarifas
      - ms-logistica
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-tarifas:3306/bd_tarifas
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpass
      SERVER_PORT: 8083
      MS_LOGISTICA_URL: http://ms-logistica:8082/api/v0.1
    ports:
      - "8083:8083"

  osrm:
    image: osrm/osrm-backend:latest
    platform: linux/amd64
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    command: >
      osrm-routed /data/argentina-251112.osrm

volumes:
  clientes_data:
  logisticas_data:
  tarifas_data:
